apiVersion: v1
kind: Service
metadata:
  labels:
    id: api
  name: api-svc
  namespace: dev
spec:
  ports:
  - name: 2222-80
    port: 2222
    protocol: TCP
    targetPort: 80
  selector:
    id: api
  type: ClusterIP
status:
  loadBalancer: {}
