apiVersion: v1
kind: Service
metadata:
  labels:
    id: frontend
  name: frontend-svc
  namespace: dev
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    id: frontend # id:api for deployment
  type: ClusterIP
status:
  loadBalancer: {}
